.github/dependabot.yml
.sclng/metadata.toml
cron.go

Add the rest of the CRUD methods:
- GetJob
- DeleteJob
- ListJobsByPrefix, where the prefix we pass in is the appID + "||"
Also added a mutex to entries and cleaned up a bit

add remaining crud funcs, add locking to entries to prevent race conditions

---

.examples/cron_example.go
collector/collector.go
collector/collector_test.go
counting/counting_test.go
counting/etcd.go
cron.go
cron_test.go
locking/local_mutexer.go
locking/mutex_cache.go
rhythm/spec_test.go

Fixes multiple races and bugs.
I validated that the garbage collection for jobs works. Once a job expires or repeat exceeds, then the counter is deleted.
It also fixes a bug where multiple overdue jobs trigger at the same second. We now drop overdue triggers.

Fix multiple races and bug with collector

---

.github/workflows/test.yaml
internal/client/client.go
internal/client/client_test.go
internal/garbage/collector.go

Delete keys in 128 key block transactions to reduce the number of transactions required to delete all keys given to Delete. This is particularly useful for the counter garbage collector.

internal/client: Delete keys in 128 key block transactions

---

internal/leadership/leadership.go
internal/leadership/leadership_test.go

Use etcd watcher for waiting for the partitions lease key to become available, rather than checking every 1/2 seconds. This reduces load on etcd when multiple replicas with the same partition ID are running.
/assign @cicoyle

internal/leadership: inform lease key for deletion

---

.golangci.yaml
api.go
api_test.go
cron.go
cron_test.go
internal/client/client.go
internal/client/client_test.go
internal/counter/counter.go
internal/garbage/collector.go
internal/informer/informer.go
internal/informer/syncer.go
internal/leadership/leadership.go
internal/leadership/leadership_test.go
internal/tests/tests.go

Update internal/client to be a generic wrapper around a real etcd client. This internal client will retry `too many requests` errors until successful, the given context is canceled, or an error occurs.

ETCD Client: Retry all `too many requests` errors

---

api.go
api_test.go
gomod2nix.toml

Fixes Delete API by dequeuing the correct job from the queue by using the job key, not job name.

API Delete: Fix dequeue deleted item

---

api.go

Fix memory leak in queue lock whereby deleting jobs on schedulers which do not host the job will grow the queue lock indefinitely.

Fix memory leak in queuelock

---

internal/key/key.go

Don't use different paths based on the OS used. This causes us to have to do OS based path matching in runtime. This switches to the `path` pkg which is not OS specific.

filepath -> path for non OS specific key paths

---

cron/cron_test.go
internal/api/validator/validator.go
internal/api/validator/validator_test.go

Now that keys correctly use `path.Join` concatenation to the Job name, we can safely add support for space characters.
Closes https://github.com/diagridio/go-etcd-cron/issues/46

Support space characters (" ") in Job names

---

internal/client/client.go
internal/garbage/collector.go
internal/informer/informer.go
internal/leadership/leadership.go

Update the informer to not push deleted keys to the collector if the key is not the same partition as the replica.
Ignore context DeadlineExceeded errors on the Leadsership Revoke client so `Run` doesn't return context errors on shutdown.

Push collector on same parition & ignore context DeadlineExceeded

---

internal/counter/counter.go
internal/counter/counter_test.go

Ensure counter has the job name set when the counter already exists and is loaded from etcd.

Counter: ensure job name set on existing counter

---

go.mod
go.sum

Update github.com/golang-jwt/jwt/v4 to v4.5.1
https://osv.dev/vulnerability/GHSA-29wx-vh33-7x7r
https://pkg.go.dev/vuln/GO-2024-3250

Fix CVE GO-2024-3250

---

cron/cron.go
cron/cron_test.go
internal/api/api.go
internal/engine/engine.go
internal/engine/fake/fake.go
internal/engine/fake/fake_test.go
internal/engine/retry/retry.go
internal/engine/retry/retry_test.go
tests/suite/retry_test.go

Adds a engine API retry which will continue to retry an API call if the API currently reports that the API is closed. This is useful for when leadership changes are in progress (typical during boot where leaders are actively being shuffled). The retry will continue to retry an active API call every 300ms when the API reports as closed (because leadership has caused the API to be closed). The retry will continue to cancel calls if the caller has cancelled the context, or if the cron is shutting down.

API engine retry

---

internal/engine/retry/retry.go
internal/scheduler/builder.go
internal/scheduler/builder_test.go

Updates the schedule API to support seconds precision, as is advertised.

Schedule: support Second precision as adverted

---

internal/informer/informer.go
internal/informer/informer_test.go
internal/queue/queue.go
tests/suite/upsert_test.go

An upsert of a Job will produce a Job whose partition will likely put the job on another replica when running as a cluster. Previously, if a job was not partitioned for that replica, the informer would always drop this update event, meaning that the job would not be deleted from the queue on the previously active replica.
Special case put events to always delete the job on the current replica if the job it put, and the partition does not match.

Fix upsert of Jobs on cluster

---

internal/leadership/elector/elector.go
tests/suite/leadership_test.go

In the event of failed reading of other leadership keys, the leader will continue to wait for the next informer reconcile instead of hard erroring out.
This is useful for events whereby the leadership key space values are not readable because they have been written by another cron who has a different value API.

Leadership: re-reconcile on failed key read

---

internal/scheduler/builder.go
internal/scheduler/builder_test.go
tests/suite/schedule_test.go

Update scheduler builder to use the correct parser so that 6 column cron style schedule strings are accepted.
Adds integration test for API.

Scheduler Builder: Use correct parser for next calculation

---

internal/engine/retry/retry.go
tests/suite/midtrigger_test.go

Update the engine retry to retry transient etcd errors;
```go
ErrTimeout                       = errors.New("etcdserver: request timed out")
ErrTimeoutDueToLeaderFail        = errors.New("etcdserver: request timed out, possibly due to previous leader failure")
ErrTimeoutDueToConnectionLost    = errors.New("etcdserver: request timed out, possibly due to connection lost")
ErrTimeoutLeaderTransfer         = errors.New("etcdserver: request timed out, leader transfer took too long")
ErrTimeoutWaitAppliedIndex       = errors.New("etcdserver: request timed out, waiting for the applied index took too long")
```

Retry: retry handle functions upon receiving transient etcd errors

---

internal/engine/retry/retry.go

Retry client requests on client connection cancelled as this can happen during leader election shuffling.

Client retry: on client connection cancelled

---

internal/api/api.go
internal/engine/engine.go
internal/informer/informer.go
internal/queue/loops/control/control.go
internal/queue/loops/counters/counters.go
internal/queue/loops/counters/counters_test.go
internal/queue/loops/fake/fake.go
internal/queue/loops/looper.go
internal/queue/loops/router/router.go
internal/queue/loops/router/router_test.go
internal/queue/queue.go

Adds a counters loop & counter cache via a sync.Pool to reduce memory allocations. The loop struct and counter struct will be created O(millions) of times during the life cycle of a cron instance. Reusing struct memory improves performance.
We should replace the current loop queue channel, with a ring buffer to prevent allocating the channel every time.

Adds counters loop & counter cache

---

internal/queue/loops/router/router.go
internal/queue/loops/router/router_test.go
tests/suite/goleak_test.go
tests/suite/upsert_test.go

Fixes a go routine leak whereby a counter loop would be created on informer deleted events, even though it has been cleared from the store as it has expired. Previously created a new counter which would be `Run` forever, using resource. Will ignore delete informer events if the counter is no processing.
Updates upsert integration tests which will fail in some timezones.
Adds a go routine leak test to ensure the number of routines falls back close to base after 1000s of executions.

queue: Fix go routine leak in router

---

internal/engine/queue/loops/counters/counters.go
internal/engine/queue/loops/counters/counters_test.go
internal/engine/queue/loops/router/router.go

Previously, a race condition could cause the counters loop to return a "catastrophic state machine error: lost cancel" when an ExecuteResponse was received after an Informed event had already cleared the cancel function. This condition can occur naturally when jobs are updated during execution.
This commit updates the behavior to treat such responses as stale and harmless. When a matching ExecuteResponse arrives with a nil cancel, the event is now silently ignored and logged at info level. This prevents unnecessary failure scenarios and improves resilience under concurrent job updates.

counters: gracefully handle stale ExecuteResponse with nil cancel

---

internal/engine/queue/loops/counters/counters.go
internal/engine/queue/loops/counters/counters_test.go
internal/engine/queue/loops/router/router.go

Previously, a race condition could cause the counters loop to return a "catastrophic state machine error: lost cancel" when an ExecuteResponse was received after an Informed event had already cleared the cancel function. This condition can occur naturally when jobs are updated during execution.
This commit updates the behavior to treat such responses as stale and harmless. When a matching ExecuteResponse arrives with a nil cancel, the event is now silently ignored and logged at info level. This prevents unnecessary failure scenarios and improves resilience under concurrent job updates.

[0.8] counters: gracefully handle stale ExecuteResponse with nil cancel

---

gomod2nix.toml
internal/engine/queue/loops/counters/counters.go
internal/engine/queue/loops/counters/counters_test.go

Prevent race conditions of upserting jobs to cause lots counter objs, and causing whole state machine to fail.

Remove catesrophic errors, in favour of drop
